---
- set_fact:
    node_disk_data: {}
    node_network_data: {}

## Currently, only one access config, ONE_TO_ONE_NAT, is supported by the Google APIs
- name: Check if only one access config is provided
  assert:
    that:
      - item.ips | length | int == 1
  with_items: "{{ nodes }}"

- include_tasks: create_disks.yml
  with_items: "{{ nodes }}"

- include_tasks: create_networks.yml
  with_items: "{{ nodes }}"

- name: Create an instance
  gcp_compute_instance:
    project: '{{ gcp_project }}'
    auth_kind: '{{ gcp_cred_kind }}'
    service_account_file: '{{ gcp_cred_file }}'

    name: '{{ node.name }}'
    zone: '{{ node.zone }}'
    machine_type: '{{ node.machine_type }}'
    deletion_protection: '{{ node.deletion_protection }}'
    disks: "{{ node_disk_data[node.name] }}"
    network_interfaces:
      ## Currently, only one access config, ONE_TO_ONE_NAT, is supported by the module
      - access_configs: "{{ node_network_data[node.name] }}"
    state: present
  loop: "{{ nodes }}"
  loop_control:
    loop_var: "node"
